name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - name: View detailed Software Versions via a pre-installed file
      run: |
        # This specific path works for Ubuntu/Linux runners
        echo "--- Detailed Software List (partial) ---"
        cat /usr/local/lib/node_modules/npm/package.json
        # Note: A full list is usually linked in the 'Set up job' log step UI.
        echo "------------------------------------------"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
    steps:
    - name: print configuration of the Runner
      run: |
        echo "--- GitHub Hosted Runner Configuration ---"
        echo "OS Name: ${{ runner.os }}"
        echo "OS Architecture: ${{ runner.arch }}"
        echo "Temp Directory: ${{ runner.temp }}"
        echo "Workspace Directory: ${{ runner.workspace }}"
        echo "Job Status: ${{ job.status }}"
        echo "------------------------------------------"

    - name: View detailed Software Versions after the dependency installation
      run: |
        # This specific path works for Ubuntu/Linux runners
        echo "--- Detailed Software List (partial) ---"
        cat /usr/local/lib/node_modules/npm/package.json
        # Note: A full list is usually linked in the 'Set up job' log step UI.
        echo "------------------------------------------"
