name: Self-hosted test
 
on:
  workflow_dispatch:
  schedule:
    - cron: "09 17 * * *"
 
jobs:

  build:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Test Script

        run: echo "Runner working on $(uname -a)"
 
