name: Self-hosted test
 
on:
  schedule:
    - cron : '29 15 * * *'
    
 
jobs:

  build:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Test Script

        run: echo "Runner working on $(uname -a)"
 
